export const portalManifest = {
  name: "be-ai-heart portal",
  audience: "customers",
  sections: [
    "overview",
    "workspaces",
    "repositories",
    "context-packs",
    "graph",
    "diagrams",
    "documents",
    "benchmarks",
    "workbench",
    "models",
    "connect",
    "usage",
    "billing",
    "policies",
    "team",
    "team-access",
    "security-audit",
    "settings",
  ],
};
